<?php

namespace common\models;

class Constants
{
    /* Header Info*/
    const API_MESSAGE_TYPE_GET_DEVICES_PRICE = "GET_DEVICES_PRICE";
    const API_MESSAGE_TYPE_GET_PAYMENT_VALIDATION = "GET_PAYMENT_VALIDATION";
    const API_MESSAGE_TYPE_GET_UNPAID_SALES_ORDER = "GET_UNPAID_SALES_ORDER";
    const API_MESSAGE_TYPE_GET_PAID_SALES_ORDER = "GET_PAID_SALES_ORDER";
    const API_MESSAGE_TYPE_GET_CUSTOMERS = "GET_CUSTOMERS";
    const API_MESSAGE_TYPE_CREATE_SALES_ORDER = "CREATE_SALES_ORDER";
    const API_MESSAGE_TYPE_CREATE_PAYMENT_ORDER = "CREATE_PAYMENT_ORDER";
    const API_MESSAGE_TYPE_CREATE_DEVICE_SWAPPING = "CREATE_DEVICE_SWAPPING";
    const API_MESSAGE_TYPE_CREATE_SALES_ORDER_TOP_UP = "CREATE_SALES_ORDER_TOP_UP";
    const API_MESSAGE_TYPE_CREATE_SALES_TRIP_ORDER = "CREATE_SALES_TRIP_ORDER";
    const API_MESSAGE_TYPE_CREATE_SALES_TRIP = "CREATE_SALES_TRIP";

    /*Http method*/
    const HTTP_METHOD_PATCH = "PATCH";
}